import Link from 'next/link';
import { ArrowRight, BrainCircuit, CircleAlert, Gauge, Lightbulb, Mail, Target, TrendingUp, Wallet } from 'lucide-react';
import { OperationsService } from '@/services/operations-service';
import { buildCeoBrief } from '@/lib/ceo-insights';

export const dynamic = 'force-dynamic';

function percent(value: number | null) { return value === null ? '—' : `${(value * 100).toFixed(1)}%`; }
function money(cents: number) { return new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(cents / 100); }

export default async function CeoPage() {
  await OperationsService.requireOwner();
  const brief = await buildCeoBrief();
  const { growth } = brief;
  return <main className="px-5 py-8 md:px-8 md:py-10">
    <header className="max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#ccff00]">CEO IA · Growth Engine · datos de producción</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em] md:text-6xl">Hoy haría esto.</h1><p className="mt-4 text-sm leading-6 text-white/55">Una decisión comercial, basada en los eventos medidos. No cambia campañas, precios ni producto automáticamente.</p></header>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl border border-[#ccff00]/25 bg-[#ccff00]/[.07] p-6"><div className="flex items-center gap-3"><Lightbulb className="text-[#ccff00]" size={20}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/45">Una única prioridad</p><h2 className="mt-1 text-2xl font-semibold">{growth.bottleneck.recommendation}</h2></div></div><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-black/25 p-4"><p className="text-xs text-white/45">Por qué</p><p className="mt-2 text-sm leading-6 text-white/80">{growth.bottleneck.explanation}</p></div><div className="rounded-2xl bg-black/25 p-4"><p className="text-xs text-white/45">Qué ganarías</p><p className="mt-2 text-xl font-semibold text-[#ddff57]">{money(growth.bottleneck.estimatedMonthlyGainCents)}/mes</p><p className="mt-1 text-xs leading-5 text-white/50">Estimación si la conversión total aumenta 1 punto porcentual.</p></div></div></article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><Gauge className="text-[#ccff00]" size={20}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Growth Score</p><h2 className="mt-1 text-2xl font-semibold">{growth.score}<span className="text-white/35">/100</span></h2></div></div><div className="mt-7 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#ccff00]" style={{ width: `${growth.score}%` }}/></div><p className="mt-4 text-sm leading-6 text-white/60">Pondera tráfico, registro, conversación, checkout, pago, activación y retención. Cobertura actual: {growth.coverage}/7 señales.</p></article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="rounded-3xl border border-rose-300/25 bg-rose-300/[.055] p-6"><div className="flex items-center gap-3"><Wallet className="text-rose-200" size={20}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-rose-100/65">Dinero que podrías estar dejando sobre la mesa</p><h2 className="mt-1 text-2xl font-semibold">{money(growth.moneyLost.todayCents)} hoy · {money(growth.moneyLost.monthCents)} al mes</h2></div></div><p className="mt-5 text-sm leading-6 text-rose-50/80">{growth.moneyLost.explanation}</p></article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><Target className="text-[#ccff00]" size={20}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Simulador</p><h2 className="mt-1 text-2xl font-semibold">Escenarios, no previsiones</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-white/45">+1% de conversión</p><p className="mt-2 text-xl font-semibold text-[#ddff57]">{money(growth.simulator.onePointCents)}/mes</p></div><div className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-white/45">10 clientes más</p><p className="mt-2 text-xl font-semibold text-[#ddff57]">{money(growth.simulator.tenCustomersCents)} MRR</p></div></div></article></section>
    <section className="mt-9 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="Visitantes hoy" value={String(brief.today.visitors)} /><Card label="Registros hoy" value={String(brief.today.registrations)} /><Card label="Checkout hoy" value={String(brief.today.checkouts)} /><Card label="Pagos hoy" value={String(brief.today.payments)} /><Card label="Conversaciones Laura" value={String(brief.today.lauraConversations)} /><Card label="MRR activo" value={money(brief.mrrCents)} /></section>
    <section className="mt-9 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><CircleAlert className="text-[#ccff00]" size={19}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Lo que necesita atención</p><h2 className="mt-1 text-xl font-semibold">Señales detectadas</h2></div></div>{brief.alerts.length ? <ul className="mt-6 grid gap-3">{brief.alerts.map((alert) => <li key={alert} className="rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm leading-6 text-amber-100">{alert}</li>)}</ul> : <p className="mt-6 rounded-2xl border border-[#ccff00]/20 bg-[#ccff00]/5 p-4 text-sm leading-6 text-[#ddff57]">No hay una alerta comercial activa con los datos disponibles.</p>}</article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><TrendingUp className="text-[#ccff00]" size={19}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Cuello de botella principal</p><h2 className="mt-1 text-xl font-semibold">{growth.bottleneck.label}</h2></div></div><p className="mt-6 rounded-2xl border border-white/8 p-4 text-sm leading-6 text-white/70">{growth.bottleneck.explanation}</p><p className="mt-4 text-xs text-white/45">Se elige una sola etapa con el menor avance medido, evitando listas de prioridades que diluyen el foco.</p></article></section>
    <section className="mt-9 rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Embudo de los últimos 7 días</p><h2 className="mt-2 text-xl font-semibold">Dónde se detiene el interés</h2></div><span className="text-sm text-white/45">Conversión visita → registro: <b className="text-[#ddff57]">{percent(brief.sevenDays.conversion)}</b></span></div><div className="mt-6 grid gap-3 md:grid-cols-5">{brief.funnels.map((item) => <article key={item.label} className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-white/45">{item.label}</p><p className="mt-5 text-3xl font-semibold">{item.value}</p><p className="mt-1 text-xs text-[#ddff57]">{item.conversion === null ? 'Base del embudo' : percent(item.conversion)}</p></article>)}</div></section>
    <section className="mt-9 rounded-3xl border border-white/10 bg-white/[.035] p-6"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Campañas y origen</p><h2 className="mt-2 text-xl font-semibold">Qué canal trae avance real</h2><div className="mt-6 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="px-3 py-3">Origen</th><th className="px-3 py-3">Visitas</th><th className="px-3 py-3">Registros</th><th className="px-3 py-3">Ventas</th><th className="px-3 py-3">MRR atribuido</th><th className="px-3 py-3">Coste</th></tr></thead><tbody>{brief.campaigns.map((item) => <tr key={item.source} className="border-b border-white/[.06] text-white/75"><td className="px-3 py-4 font-medium">{item.source}</td><td className="px-3 py-4">{item.visitors}</td><td className="px-3 py-4">{item.registrations}</td><td className="px-3 py-4">{item.sales}</td><td className="px-3 py-4">{item.mrrCents === null ? 'Sin atribución suficiente' : money(item.mrrCents)}</td><td className="px-3 py-4 text-white/45">No conectado</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5 text-white/40">El coste no se estima: aparecerá cuando exista una fuente de gasto publicitario conectada.</p></section>
    <section className="mt-9 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Leads calientes</p><h2 className="mt-2 text-xl font-semibold">Personas con mayor señal de intención</h2><p className="mt-2 text-sm text-white/50">Solo ranking interno. No contacta a nadie automáticamente.</p><div className="mt-6 grid gap-3">{brief.hotLeads.length ? brief.hotLeads.map((lead) => <div key={`${lead.label}-${lead.score}`} className="flex items-center justify-between gap-4 rounded-2xl border border-white/8 px-4 py-3"><div><p className="text-sm font-medium">{lead.label}</p><p className="mt-1 text-xs text-white/45">{lead.reason}</p></div><div className="text-right"><p className="text-lg font-semibold text-[#ddff57]">{lead.score}</p><p className="text-[10px] uppercase tracking-wide text-white/40">{lead.state}</p></div></div>) : <p className="rounded-2xl border border-white/8 p-4 text-sm text-white/50">Aún no hay señales suficientes para ordenar leads.</p>}</div></article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><BrainCircuit className="text-[#ccff00]" size={19}/><p className="mt-6 font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Proyección comercial</p><h2 className="mt-2 text-xl font-semibold">Una estimación, no una promesa.</h2><p className="mt-5 text-sm leading-7 text-white/65">{brief.prediction}</p><Link href="/ops/business" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-sm font-semibold hover:bg-white/5">Ver datos detallados <ArrowRight size={15}/></Link></article></section>
    <section className="mt-9 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Modo inversor · último mes</p><h2 className="mt-2 text-xl font-semibold">Resumen financiero con evidencia disponible</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><Card label="MRR" value={money(brief.investor.mrrCents)} /><Card label="ARR" value={money(brief.investor.arrCents)} /><Card label="CAC" value={brief.investor.cac} /><Card label="LTV" value={brief.investor.ltv} /><Card label="Churn" value={brief.investor.churn} /><Card label="Conversión" value={brief.investor.conversion} /></div></article><article className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><Mail className="text-[#ccff00]" size={19}/><p className="mt-6 font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Informe ejecutivo</p><h2 className="mt-2 text-xl font-semibold">Mensual, profesional y exportable.</h2><ul className="mt-5 grid gap-2 text-sm leading-6 text-white/65">{brief.investor.objectives.map((objective) => <li key={objective}>• {objective}</li>)}</ul><div className="mt-6 flex flex-wrap gap-3"><a href="?report=investor" className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold hover:bg-white/5">Abrir vista para PDF</a><span className={`rounded-full px-4 py-2 text-sm ${brief.reportEnabled ? 'bg-[#ccff00] text-[#111315]' : 'bg-white/8 text-white/45'}`}>{brief.reportEnabled ? 'Resumen semanal por email activo' : 'Resumen semanal por email desactivado'}</span></div></article></section>
  </main>;
}

function Card({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[11px] text-white/45">{label}</p><p className="mt-4 text-xl font-semibold tracking-[-.04em]">{value}</p></article>; }
