import Link from 'next/link';
import { ArrowRight, BrainCircuit, CircleAlert, Lightbulb, Mail, TrendingUp } from 'lucide-react';
import { OperationsService } from '@/services/operations-service';
import { buildCeoBrief } from '@/lib/ceo-insights';

export const dynamic = 'force-dynamic';

function percent(value: number | null) { return value === null ? '—' : `${(value * 100).toFixed(1)}%`; }
function money(cents: number) { return new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(cents / 100); }

export default async function CeoPage() {
  await OperationsService.requireOwner();
  const brief = await buildCeoBrief();
  return <main className="px-5 py-8 md:px-8 md:py-10">
    <header className="max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#ccff00]">CEO IA · datos reales actualizados ahora</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em] md:text-6xl">Qué ha pasado y qué haría mañana.</h1><p className="mt-4 text-sm leading-6 text-white/55">Una lectura comercial de tráfico, conversaciones, registro y pago. Las recomendaciones nunca cambian el producto por sí solas.</p></header>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="Visitantes hoy" value={String(brief.today.visitors)} /><Card label="Registros hoy" value={String(brief.today.registrations)} /><Card label="Checkout hoy" value={String(brief.today.checkouts)} /><Card label="Pagos hoy" value={String(brief.today.payments)} /><Card label="Conversaciones Laura" value={String(brief.today.lauraConversations)} /><Card label="MRR activo" value={money(brief.mrrCents)} /></section>
    <section className="mt-9 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><CircleAlert className="text-[#ccff00]" size={19}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Lo que necesita atención</p><h2 className="mt-1 text-xl font-semibold">Señales detectadas</h2></div></div>{brief.alerts.length ? <ul className="mt-6 grid gap-3">{brief.alerts.map((alert) => <li key={alert} className="rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm leading-6 text-amber-100">{alert}</li>)}</ul> : <p className="mt-6 rounded-2xl border border-[#ccff00]/20 bg-[#ccff00]/5 p-4 text-sm leading-6 text-[#ddff57]">No hay una alerta comercial activa con los datos disponibles.</p>}</article><article className="rounded-3xl border border-[#ccff00]/25 bg-[#ccff00]/7 p-6"><div className="flex items-center gap-3"><Lightbulb className="text-[#ccff00]" size={19}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/45">Qué haría mañana</p><h2 className="mt-1 text-xl font-semibold">Acciones recomendadas</h2></div></div><ol className="mt-6 grid gap-3">{brief.recommendations.map((recommendation, index) => <li key={recommendation} className="flex gap-3 rounded-2xl bg-black/20 p-4 text-sm leading-6 text-white/75"><b className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#ccff00] text-xs text-[#111315]">{index + 1}</b>{recommendation}</li>)}</ol></article></section>
    <section className="mt-9 rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Embudo de los últimos 7 días</p><h2 className="mt-2 text-xl font-semibold">Dónde se detiene el interés</h2></div><span className="text-sm text-white/45">Conversión visita → registro: <b className="text-[#ddff57]">{percent(brief.sevenDays.conversion)}</b></span></div><div className="mt-6 grid gap-3 md:grid-cols-5">{brief.funnels.map((item) => <article key={item.label} className="rounded-2xl border border-white/10 p-4"><p className="text-xs text-white/45">{item.label}</p><p className="mt-5 text-3xl font-semibold">{item.value}</p><p className="mt-1 text-xs text-[#ddff57]">{item.conversion === null ? 'Base del embudo' : percent(item.conversion)}</p></article>)}</div></section>
    <section className="mt-9 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><TrendingUp className="text-[#ccff00]" size={19}/><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Lo que está funcionando</p><h2 className="mt-1 text-xl font-semibold">Ranking comercial</h2></div></div><dl className="mt-6 grid gap-3">{brief.ranking.map((item) => <div key={item.label} className="flex items-center justify-between gap-4 rounded-2xl border border-white/8 px-4 py-3"><dt className="text-sm text-white/50">{item.label}</dt><dd className="text-right text-sm font-medium text-white/85">{item.value}</dd></div>)}</dl></article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><BrainCircuit className="text-[#ccff00]" size={19}/><p className="mt-6 font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Proyección comercial</p><h2 className="mt-2 text-xl font-semibold">Una estimación, no una promesa.</h2><p className="mt-5 text-sm leading-7 text-white/65">{brief.prediction}</p><Link href="/ops/business" className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-sm font-semibold hover:bg-white/5">Ver datos detallados <ArrowRight size={15}/></Link></article></section>
    <section className="mt-9 rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-white/40">Informe semanal</p><h2 className="mt-2 text-xl font-semibold">Resumen preparado para guardar o enviar.</h2></div><Mail className="text-[#ccff00]" size={19}/></div><div className="mt-6 grid gap-3 text-sm leading-6 text-white/65"><p><b className="text-white">Lo mejor:</b> {brief.weekly.best}</p><p><b className="text-white">Lo peor:</b> {brief.weekly.worst}</p><p><b className="text-white">Cambio:</b> {brief.weekly.changes}</p></div><div className="mt-6 flex flex-wrap gap-3"><a href="?report=weekly" className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold hover:bg-white/5">Vista imprimible / PDF</a><span className={`rounded-full px-4 py-2 text-sm ${brief.reportEnabled ? 'bg-[#ccff00] text-[#111315]' : 'bg-white/8 text-white/45'}`}>{brief.reportEnabled ? 'Entrega semanal por email activada' : 'Entrega semanal por email desactivada'}</span></div></section>
  </main>;
}

function Card({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[11px] text-white/45">{label}</p><p className="mt-6 text-2xl font-semibold tracking-[-.04em]">{value}</p></article>; }
