import Link from 'next/link';
import { ArrowRight, Brain, CalendarCheck, CheckCircle2, Database, LayoutDashboard, Network, Users } from 'lucide-react';
import { AutopilotShowcase } from '@/components/autopilot-showcase';
import { MissionsShowcase } from '@/components/missions-showcase';

const capabilities = [
  [Brain, 'Contexto compartido', 'Cada empleado consulta el historial de tu empresa antes de continuar una conversación.'],
  [Database, 'Customer 360', 'Llamadas, mensajes, presupuestos y tareas se relacionan con el mismo cliente.'],
  [Network, 'Automatizaciones', 'Una necesidad puede llegar al miembro del equipo adecuado sin repetir información.'],
  [CalendarCheck, 'Integraciones', 'Teléfono, calendario y canales de contacto conectados en función de tu equipo.'],
  [LayoutDashboard, 'Control claro', 'La actividad real se consulta desde tu espacio privado y el Dashboard CEO.'],
  [Users, 'Departamentos', 'Puedes empezar por una función y convertirla en un equipo cuando tengas más volumen.'],
];

export default function EmpresaIaPage() { return <main><header className="border-b border-[var(--line)]"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-6 md:px-10"><Link href="/" className="text-lg font-bold tracking-[-.07em]">EMPLEADO<span className="text-[#789500]">24</span></Link><Link href="/#empleados" className="text-sm font-semibold">Conocer empleados</Link></div></header><section className="grid-bg relative overflow-hidden"><div className="noise"/><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-6 md:px-10 md:py-32"><p className="eyebrow">Empresa IA</p><h1 className="mt-4 max-w-5xl text-5xl font-semibold tracking-[-.075em] md:text-7xl">La primera empresa con empleados IA trabajando juntos.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">No son herramientas separadas. Forman un equipo que comprende el historial de tu empresa, coordina trabajo y deja a las personas las decisiones importantes.</p><Link href="/#packs" className="mt-9 inline-flex items-center gap-2 rounded-full bg-[#111315] px-6 py-3 font-semibold text-white dark:bg-[#ccff00] dark:text-[#111315]">Ver equipos disponibles <ArrowRight size={16}/></Link></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-6 md:px-10"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([Icon, title, detail]) => { const CardIcon = Icon as typeof Brain; return <article className="surface rounded-3xl p-6" key={String(title)}><CardIcon size={21} className="text-[#789500]"/><h2 className="mt-8 text-xl font-semibold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{String(detail)}</p></article>; })}</div></section><AutopilotShowcase/><MissionsShowcase/><section className="mx-auto max-w-7xl px-5 pb-20 sm:px-6 md:px-10"><div className="rounded-[2rem] border border-[#cfe69a] bg-[#f8ffe9] p-8 dark:border-[#405422] dark:bg-[#202900]"><div className="flex items-center gap-2 text-[#789500]"><CheckCircle2 size={19}/><span className="text-xs font-semibold uppercase tracking-[.12em]">Una incorporación progresiva</span></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em]">Empieza por la necesidad de hoy.</h2><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">Puedes contratar un empleado individual, un departamento disponible o ampliar tu equipo cuando el volumen lo pida.</p><Link href="/#empleados" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">Conocer el equipo <ArrowRight size={15}/></Link></div></section></main>; }
