import Link from 'next/link';
import { Calculator, CheckCircle2, FileText, Send, Sparkles } from 'lucide-react';
import { CompanyService } from '@/services/company-service';
import { createClient } from '@/lib/supabase/server';
import { createQuote, sendQuote } from '@/app/actions/quotes';

function money(cents: number) { return new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(cents / 100); }

export default async function BudgetSpecialistPage() {
  const membership = await CompanyService.current();
  const relation = membership?.companies;
  const company = Array.isArray(relation) ? relation[0] : relation;
  if (!company) return null;
  const supabase = await createClient() as any;
  const [{ data: employee }, { data: quotes }, { data: catalogue }, { data: templates }] = await Promise.all([
    supabase.from('employees').select('id,name,status').eq('company_id', company.id).eq('employee_type', 'budget_specialist').maybeSingle(),
    supabase.from('quotes').select('id,title,status,total_cents,cost_cents,profit_cents,margin_bps,current_version,created_at,customers(display_name,email)').eq('company_id', company.id).order('updated_at', { ascending: false }).limit(30),
    supabase.from('quote_catalog_items').select('id,name,category,unit,unit_cost_cents').eq('company_id', company.id).eq('active', true).order('category').limit(100),
    supabase.from('quote_templates').select('id,name,default_margin_bps').eq('company_id', company.id).order('name').limit(30),
  ]);
  if (!employee) return <main className="grid min-h-[75vh] place-items-center px-6 py-16"><div className="max-w-lg text-center"><Calculator className="mx-auto text-[var(--muted)]" size={34}/><p className="eyebrow mt-8">Tu equipo</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Tu Especialista Presupuestos aún no se ha incorporado.</h1><p className="mt-3 text-[var(--muted)]">Incorpóralo y preparará presupuestos con los precios y márgenes de tu empresa.</p><Link href="/app/facturacion" className="mt-7 inline-flex rounded-full bg-[#111315] px-5 py-3 text-sm font-semibold text-white dark:bg-[#f4f5f0] dark:text-[#111315]">Incorporar Especialista Presupuestos</Link></div></main>;
  type Quote = { id: string; title: string; status: string; total_cents: number; cost_cents: number; profit_cents: number; margin_bps: number; current_version: number; created_at: string; customers: { display_name: string | null; email: string | null } | null };
  const rows = (quotes ?? []) as Quote[];
  const total = rows.reduce((sum, quote) => sum + quote.total_cents, 0);
  const profit = rows.reduce((sum, quote) => sum + quote.profit_cents, 0);
  return <main className="mx-auto max-w-7xl px-5 py-10 md:px-10 md:py-14">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Tu equipo</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.06em] md:text-5xl">{employee.name}</h1><p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">Te ayuda a preparar un presupuesto claro, rentable y listo para compartir en menos de dos minutos.</p></div><span className="rounded-full bg-[#e9ffcf] px-4 py-2 text-sm font-semibold text-[#486500]">● Preparado</span></header>
    <section className="mt-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={FileText} label="Presupuestos" value={String(rows.length)}/><Metric icon={Calculator} label="Importe presupuestado" value={money(total)}/><Metric icon={Sparkles} label="Beneficio previsto" value={money(profit)}/><Metric icon={CheckCircle2} label="Aceptados" value={String(rows.filter((quote) => quote.status === 'accepted').length)}/></section>
    <section className="mt-10 grid gap-6 xl:grid-cols-[1fr_1.35fr]"><div className="surface rounded-[2rem] p-6"><p className="eyebrow">Nuevo presupuesto</p><h2 className="mt-2 text-2xl font-semibold">Cuéntame qué necesita tu cliente.</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Puedes escribir el encargo como lo explicarías a un técnico. El margen y el descuento se detectan automáticamente si los indicas.</p><form action={createQuote} className="mt-6 grid gap-3"><input name="title" required minLength={2} placeholder="Ej. Instalación solar para Ana" className="input"/><textarea name="brief" required minLength={8} className="input min-h-24" placeholder="Ej. Presupuesto para instalar placas solares. Margen del 35%."/><div className="grid gap-3 sm:grid-cols-2"><input name="customer_name" placeholder="Nombre del cliente" className="input"/><input name="customer_email" type="email" placeholder="Email del cliente" className="input"/></div><div className="grid gap-3 sm:grid-cols-2"><input name="customer_phone" placeholder="Teléfono" className="input"/><input name="chapter" placeholder="Capítulo (ej. Instalación)" className="input"/></div><input name="concept" required placeholder="Partida o concepto" className="input"/><div className="grid gap-3 sm:grid-cols-4"><input name="quantity" required type="number" min="0.001" step="0.001" defaultValue="1" className="input" aria-label="Cantidad"/><input name="unit" defaultValue="unidad" className="input" aria-label="Unidad"/><input name="unit_cost_euros" required type="number" min="0" step="0.01" placeholder="Coste €" className="input"/><input name="planned_days" type="number" min="0" defaultValue="0" className="input" aria-label="Días previstos"/></div><div className="grid gap-3 sm:grid-cols-3"><input name="margin_percent" type="number" min="0" max="99" step="0.01" defaultValue="35" className="input" aria-label="Margen porcentual"/><input name="discount_percent" type="number" min="0" max="99" step="0.01" defaultValue="0" className="input" aria-label="Descuento porcentual"/><input name="tax_percent" type="number" min="0" max="99" step="0.01" defaultValue="21" className="input" aria-label="Impuesto porcentual"/></div><button className="mt-2 rounded-full bg-[#111315] px-5 py-3 text-sm font-semibold text-white dark:bg-[#f4f5f0] dark:text-[#111315]">Preparar presupuesto</button></form></div>
      <div><div className="mb-5"><p className="eyebrow">Presupuestos de {company.name}</p><h2 className="mt-2 text-2xl font-semibold">Tu trabajo reciente</h2></div>{rows.length ? <div className="grid gap-4">{rows.map((quote) => <article key={quote.id} className="surface rounded-3xl p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="text-xl font-semibold">{quote.title}</h3><span className="rounded-full bg-black/5 px-3 py-1 text-xs text-[var(--muted)] dark:bg-white/5">{quote.status === 'sent' ? 'Enviado' : quote.status === 'accepted' ? 'Aceptado' : 'Borrador'}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{quote.customers?.display_name || quote.customers?.email || 'Cliente por completar'} · Versión {quote.current_version}</p></div><p className="text-2xl font-semibold">{money(quote.total_cents)}</p></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><p>Coste <strong className="block text-base">{money(quote.cost_cents)}</strong></p><p>Beneficio <strong className="block text-base">{money(quote.profit_cents)}</strong></p><p>Margen <strong className="block text-base">{(quote.margin_bps / 100).toFixed(1)}%</strong></p></div>{quote.status === 'draft' && <form action={sendQuote} className="mt-5"><input type="hidden" name="quote_id" value={quote.id}/><button className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] px-4 py-2.5 text-sm font-semibold"><Send size={15}/> Preparar envío y seguimiento</button></form>}</article>)}</div> : <div className="rounded-3xl border border-dashed border-[var(--line)] p-10 text-center"><Calculator className="mx-auto text-[#789500]"/><p className="mt-5 font-medium">Todavía no hay presupuestos.</p><p className="mt-2 text-sm text-[var(--muted)]">Empieza con el encargo de tu primer cliente.</p></div>}</div></section>
    <section className="mt-10 grid gap-4 md:grid-cols-2"><article className="rounded-3xl border border-dashed border-[var(--line)] p-6"><p className="font-semibold">Tu catálogo</p><p className="mt-2 text-sm text-[var(--muted)]">{catalogue?.length ?? 0} partidas guardadas. Tus precios, categorías y proveedores se guardan solo para {company.name}.</p></article><article className="rounded-3xl border border-dashed border-[var(--line)] p-6"><p className="font-semibold">Tus plantillas</p><p className="mt-2 text-sm text-[var(--muted)]">{templates?.length ?? 0} plantillas disponibles para mantener las condiciones y la imagen de tu empresa.</p></article></section>
  </main>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof FileText; label: string; value: string }) { return <article className="surface rounded-3xl p-5"><Icon size={18} className="text-[#789500]"/><p className="mt-6 text-3xl font-semibold tracking-[-.05em]">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></article>; }
